name: .net pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-dotnet-app:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release -o /app/build --no-restore
      
    - name: publish
      run: dotnet publish -c Release -o /app/publish

    - name: Debug
      run: ls -lah /app/publish

    - name: Upload result of publish
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: /app/publish
    


    