name: .net pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-dotnet-app:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: net-app

    steps:
    - name: Git clone
      uses: actions/checkout@v3

    - name: Debug pwd and what's inside
      run: |
        pwd
        ls -lah 
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
    - name: Make dirs
      run: |
        mkdir -p app/build
        mkdir -p app/publish
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release -o app/build --no-restore
      
    - name: publish
      run: dotnet publish -c Release -o app/publish

    - name: Debug what's in publish folder
      run: ls -lah app/publish

    - name: Upload result of publish
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: net-app/app/publish/
        if-no-files-found: error
  
  build-docker-image:
    needs: build-dotnet-app
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Download artifacts in publish
        uses: actions/download-artifact@v4
        with:
          name: publish
          path: net-app/app/publish/

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Debug pwd and what's inside
        run: |
          pwd
          ls -lah 
          ls -R net-app/
      
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}